
package vistas;

import java.util.ArrayList;
import modelo.Equipo;
import modelo.Marca;
import modelo.Proceso;
import modelo.TipoEquipo;
import modelo.TipoProceso;

/**
 *
 * @author Ariel Mathias
 */
public class BuscarEquipo extends javax.swing.JFrame {

    /**
     * Creates new form BuscarEquipo
     */
    public BuscarEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_visualizarEquipo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtA_listaEquipos = new javax.swing.JTextArea();
        jbtn_buscarEquipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_visualizarEquipo.setText("Visualizar Equipo");

        jtxtA_listaEquipos.setColumns(20);
        jtxtA_listaEquipos.setRows(5);
        jScrollPane1.setViewportView(jtxtA_listaEquipos);

        jbtn_buscarEquipo.setText("Buscar");
        jbtn_buscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_visualizarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_buscarEquipo)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_visualizarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarEquipo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_buscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarEquipoActionPerformed
        
        controlador.ContBuscarEquipo buscar = new controlador.ContBuscarEquipo();
        bbdd.Conexion conec = new bbdd.Conexion();
        
        ArrayList<modelo.Proceso> listarProcesos = new ArrayList<>();
        TipoEquipo tipoEquipo = new TipoEquipo();
        TipoProceso tipoProceso = new TipoProceso();
        
        Proceso proceso = new Proceso();
        Equipo equipo = new Equipo();
        Marca mrc = new Marca();
        String idEquipo = null;
        
        
        listarProcesos = buscar.buscarEquipo(idEquipo);
        
        tipoProceso = buscar.buscarTipoProceso(tipoProceso.getId_tipo_proceso());
        equipo = buscar.buscarEquipo(equipo.getId_equipo());
       
        mrc = buscar.buscarMarca(mrc.getId_marca());
        tipoEquipo = buscar.buscarTipoEquipo(tipoEquipo.getId_tipo_equipo());

        // Construir la cadena con la información
        StringBuilder info = new StringBuilder();
        info.append("ID Equipo: ").append(equipo.getId_equipo()).append("\t");
        info.append("Nombre: ").append(tipoEquipo.getTipo_equipo()).append("\t");
        info.append("Modelo: ").append(equipo.getModelo()).append("\t");
        info.append("Código de Serie: ").append(equipo.getNumero_serie()).append("\t");
        info.append("Tipo Proceso: ").append(tipoProceso.getNombre()).append("\t");

        // Mostrar la información en el JTextArea
        jtxtA_listaEquipos.setText(info.toString());
        
    }//GEN-LAST:event_jbtn_buscarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_buscarEquipo;
    private javax.swing.JLabel jlbl_visualizarEquipo;
    private javax.swing.JTextArea jtxtA_listaEquipos;
    // End of variables declaration//GEN-END:variables
}
