/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Equipo;
import modelo.Marca;
import modelo.Proceso;
import modelo.TipoEquipo;

/**
 *
 * @author jcifu
 */


public class IngresarEquipo extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_IngresarEquipo
     */
    
    FondoPanel fondoI = new FondoPanel();

    public IngresarEquipo() {
        this.setContentPane(fondoI);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_idEquipo = new javax.swing.JLabel();
        jtxt_idEquipo = new javax.swing.JTextField();
        jlb_usuario = new javax.swing.JLabel();
        jtxt_usuario = new javax.swing.JTextField();
        jbtn_buscarID = new javax.swing.JButton();
        jlb_tipoEquipo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxp_tipoEquipo = new javax.swing.JTextPane();
        jlb_marca = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxp_marca = new javax.swing.JTextPane();
        jlb_modelo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxp_modelo = new javax.swing.JTextPane();
        jlb_serial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxp_serialN = new javax.swing.JTextPane();
        jtbn_guardar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Equipo");
        setPreferredSize(new java.awt.Dimension(955, 715));

        jlb_idEquipo.setBackground(new java.awt.Color(0, 0, 102));
        jlb_idEquipo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jlb_idEquipo.setText("ID EQUIPO:");

        jtxt_idEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idEquipoActionPerformed(evt);
            }
        });

        jlb_usuario.setBackground(new java.awt.Color(0, 0, 102));
        jlb_usuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jlb_usuario.setText("USUARIO:");

        jtxt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usuarioActionPerformed(evt);
            }
        });

        jbtn_buscarID.setBackground(new java.awt.Color(0, 0, 102));
        jbtn_buscarID.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_buscarID.setText("Buscar");
        jbtn_buscarID.setBorder(new javax.swing.border.MatteBorder(null));
        jbtn_buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarIDActionPerformed(evt);
            }
        });

        jlb_tipoEquipo.setBackground(new java.awt.Color(0, 0, 102));
        jlb_tipoEquipo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jlb_tipoEquipo.setText("Tipo Equipo:");

        jScrollPane5.setViewportView(jtxp_tipoEquipo);

        jlb_marca.setBackground(new java.awt.Color(0, 0, 102));
        jlb_marca.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jlb_marca.setText("Marca: ");

        jScrollPane3.setViewportView(jtxp_marca);

        jlb_modelo.setBackground(new java.awt.Color(0, 0, 102));
        jlb_modelo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jlb_modelo.setText("Modelo:");

        jScrollPane4.setViewportView(jtxp_modelo);

        jlb_serial.setBackground(new java.awt.Color(0, 0, 102));
        jlb_serial.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jlb_serial.setText("Numero de Serie:");

        jScrollPane1.setViewportView(jtxp_serialN);

        jtbn_guardar.setBackground(new java.awt.Color(0, 0, 102));
        jtbn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jtbn_guardar.setText("Guardar");
        jtbn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbn_guardarActionPerformed(evt);
            }
        });

        jbtn_cancelar.setBackground(new java.awt.Color(0, 0, 102));
        jbtn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_cancelar.setText("Cerrar");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jtbn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlb_tipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jlb_marca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlb_modelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_idEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlb_serial)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jtxt_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_idEquipo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35)
                        .addComponent(jbtn_buscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_idEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_idEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_tipoEquipo)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_marca)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_modelo)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_serial)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_idEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idEquipoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtxt_idEquipoActionPerformed

    private void jtxt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usuarioActionPerformed

    private void jbtn_buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarIDActionPerformed
        // TODO add your handling code here:
        this.jtxt_idEquipo.requestFocus();

        controlador.ContIngresar proceso = new controlador.ContIngresar();
        Equipo equi = new Equipo();
        TipoEquipo tipo = new TipoEquipo();
        Marca marca = new Marca();

        String idEquipo, equipo;
        //int estado;

        try {
            if (jtxt_idEquipo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar un ID de Equipo", "Atención", JOptionPane.WARNING_MESSAGE);
            } else {

                idEquipo = jtxt_idEquipo.getText();

                equi = proceso.buscarEquipoEnProceso(idEquipo);
                this.jtxp_modelo.setText(equi.getModelo());

                tipo = proceso.buscarTipo(equi.getId_tipo_equipo());
                this.jtxp_tipoEquipo.setText(tipo.getTipo_equipo());

                marca = proceso.buscarMarca(equi.getId_marca());
                this.jtxp_marca.setText(marca.getNombre_marca());

                this.jtxp_serialN.setText(equi.getNumero_serie());

                if (this.jtxp_modelo.getText().isEmpty() && this.jtxp_tipoEquipo.getText().isEmpty() && this.jtxp_marca.getText().isEmpty() && this.jtxp_serialN.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Equipo no encontrado", "Atención", JOptionPane.WARNING_MESSAGE);
                }

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Equipo no encontrado", "Atención", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_buscarIDActionPerformed

    private void jtbn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn_guardarActionPerformed
        // TODO add your handling code here:

        controlador.ContIngresar ingEquip = new controlador.ContIngresar();
        Proceso proceso = new Proceso();

        if (this.jtxt_idEquipo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ID Equipo no ingresado", "Atención", JOptionPane.WARNING_MESSAGE);
        } else {
            if (this.jtxt_usuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "ID Usuario no ingresado", "Atención", JOptionPane.WARNING_MESSAGE);
            } else {
                if (this.jtxp_modelo.getText().isEmpty() && this.jtxp_tipoEquipo.getText().isEmpty() && this.jtxp_marca.getText().isEmpty() && this.jtxp_serialN.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "ID Equipo no encontrado, favor verificar", "Atención", JOptionPane.WARNING_MESSAGE);
                } else {

                    int idEq = Integer.parseInt(this.jtxt_idEquipo.getText());
                    int idUsua = Integer.parseInt(this.jtxt_usuario.getText());

                    proceso.setId_equipo(idEq);
                    proceso.setId_usuario(idUsua);

                    try {

                        ingEquip.agregarProceso(proceso);
                        JOptionPane.showMessageDialog(rootPane, "Proceso Ingresado", "", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();

                    } catch (HeadlessException e) {
                        JOptionPane.showMessageDialog(rootPane, "Proceso No Ingresado", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                }
            }
        }

        //controlador.ContIngresar proceso = new controlador.ContIngresar();

        
    }//GEN-LAST:event_jtbn_guardarActionPerformed

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint (Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/Ingresar.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrame_IngresarEquipo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbtn_buscarID;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JLabel jlb_idEquipo;
    private javax.swing.JLabel jlb_marca;
    private javax.swing.JLabel jlb_modelo;
    private javax.swing.JLabel jlb_serial;
    private javax.swing.JLabel jlb_tipoEquipo;
    private javax.swing.JLabel jlb_usuario;
    private javax.swing.JButton jtbn_guardar;
    private javax.swing.JTextPane jtxp_marca;
    private javax.swing.JTextPane jtxp_modelo;
    private javax.swing.JTextPane jtxp_serialN;
    private javax.swing.JTextPane jtxp_tipoEquipo;
    private javax.swing.JTextField jtxt_idEquipo;
    private javax.swing.JTextField jtxt_usuario;
    // End of variables declaration//GEN-END:variables
}
