/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Equipo;
import modelo.Marca;
import modelo.Proceso;
import modelo.TipoEquipo;

/**
 *
 * @author jcifu
 */
public class JFrame_IngresarEquipo extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_IngresarEquipo
     */
    public JFrame_IngresarEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_panelMenu = new javax.swing.JPanel();
        jlb_idEquipo = new javax.swing.JLabel();
        jtxt_idEquipo = new javax.swing.JTextField();
        jbtn_buscarID = new javax.swing.JButton();
        jlb_usuario = new javax.swing.JLabel();
        jtxt_usuario = new javax.swing.JTextField();
        jlb_marca = new javax.swing.JLabel();
        jlb_modelo = new javax.swing.JLabel();
        jlb_serial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxp_serialN = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxp_marca = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxp_modelo = new javax.swing.JTextPane();
        jtbn_guardar = new javax.swing.JButton();
        jbtn_cerrar = new javax.swing.JButton();
        jlb_tipoEquipo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxp_tipoEquipo = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Equipo");

        jlb_idEquipo.setText("ID EQUIPO:");

        jtxt_idEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idEquipoActionPerformed(evt);
            }
        });

        jbtn_buscarID.setText("Buscar");
        jbtn_buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarIDActionPerformed(evt);
            }
        });

        jlb_usuario.setText("USUARIO:");

        jtxt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usuarioActionPerformed(evt);
            }
        });

        jlb_marca.setText("Marca: ");

        jlb_modelo.setText("Modelo:");

        jlb_serial.setText("Numero de Serie:");

        jScrollPane1.setViewportView(jtxp_serialN);

        jScrollPane3.setViewportView(jtxp_marca);

        jScrollPane4.setViewportView(jtxp_modelo);

        jtbn_guardar.setText("Guardar");
        jtbn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbn_guardarActionPerformed(evt);
            }
        });

        jbtn_cerrar.setText("Cerrar");
        jbtn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cerrarActionPerformed(evt);
            }
        });

        jlb_tipoEquipo.setText("Tipo Equipo:");

        jScrollPane5.setViewportView(jtxp_tipoEquipo);

        javax.swing.GroupLayout jpnl_panelMenuLayout = new javax.swing.GroupLayout(jpnl_panelMenu);
        jpnl_panelMenu.setLayout(jpnl_panelMenuLayout);
        jpnl_panelMenuLayout.setHorizontalGroup(
            jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jtbn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(jbtn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                        .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                                    .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                                            .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jlb_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jlb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(56, 56, 56))
                                        .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                                            .addComponent(jlb_tipoEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(41, 41, 41)))
                                    .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4)
                                        .addComponent(jScrollPane5)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnl_panelMenuLayout.createSequentialGroup()
                                    .addComponent(jlb_serial)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlb_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlb_idEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxt_idEquipo)
                                    .addComponent(jtxt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_buscarID)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnl_panelMenuLayout.setVerticalGroup(
            jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_panelMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_idEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_idEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarID))
                .addGap(18, 18, 18)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_tipoEquipo)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_marca)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_modelo)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb_serial)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jpnl_panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnl_panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnl_panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_idEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idEquipoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtxt_idEquipoActionPerformed

    private void jtxt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usuarioActionPerformed

    private void jbtn_buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarIDActionPerformed
        // TODO add your handling code here:
        this.jtxt_idEquipo.requestFocus();
        
        controlador.ContIngresar ingresar = new controlador.ContIngresar();
        Equipo equi = new Equipo();
        TipoEquipo tipo = new TipoEquipo();
        Marca marca = new Marca();
        
        String idEquipo,equipo;
        int estado;
        
        idEquipo = jtxt_idEquipo.getText();
        
        equi = ingresar.buscarEquipoEnProceso(idEquipo);
        this.jtxp_modelo.setText(equi.getModelo());
        
        tipo = ingresar.buscarTipo(equi.getId_tipo_equipo());
        this.jtxp_tipoEquipo.setText(tipo.getTipo_equipo());
        
        marca = ingresar.buscarMarca(equi.getId_marca());
        this.jtxp_marca.setText(marca.getNombre_marca());
        
        this.jtxp_serialN.setText(equi.getNumero_serie());
    }//GEN-LAST:event_jbtn_buscarIDActionPerformed

    private void jtbn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbn_guardarActionPerformed
        // TODO add your handling code here:
        
        controlador.ContIngresar ingEquip = new controlador.ContIngresar();
        Proceso proceso = new Proceso();
        
        int idEq = Integer.parseInt(this.jtxt_idEquipo.getText());
        int idUsua = Integer.parseInt(this.jtxt_usuario.getText());
        
        proceso.setId_equipo(idEq);
        proceso.setId_usuario(idUsua);
        
        try {
            
            ingEquip.agregarProceso(proceso);
            JOptionPane.showMessageDialog(rootPane, "Proceso Ingresado", "", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Proceso No Ingresado", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jtbn_guardarActionPerformed

    private void jbtn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtn_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_IngresarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_IngresarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbtn_buscarID;
    private javax.swing.JButton jbtn_cerrar;
    private javax.swing.JLabel jlb_idEquipo;
    private javax.swing.JLabel jlb_marca;
    private javax.swing.JLabel jlb_modelo;
    private javax.swing.JLabel jlb_serial;
    private javax.swing.JLabel jlb_tipoEquipo;
    private javax.swing.JLabel jlb_usuario;
    private javax.swing.JPanel jpnl_panelMenu;
    private javax.swing.JButton jtbn_guardar;
    private javax.swing.JTextPane jtxp_marca;
    private javax.swing.JTextPane jtxp_modelo;
    private javax.swing.JTextPane jtxp_serialN;
    private javax.swing.JTextPane jtxp_tipoEquipo;
    private javax.swing.JTextField jtxt_idEquipo;
    private javax.swing.JTextField jtxt_usuario;
    // End of variables declaration//GEN-END:variables
}
