/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Equipo;
import modelo.Marca;
import modelo.Proceso;
import modelo.TipoEquipo;

/**
 *
 * @author pipeg
 */
public class VProceso extends javax.swing.JFrame {

    /**
     * Creates new form Proceso
     */
    public VProceso() {
        initComponents();
        this.jrbtn_desifectante.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupProceso = new javax.swing.ButtonGroup();
        jlbl_ingresarID = new javax.swing.JLabel();
        jbtn_buscar = new javax.swing.JButton();
        jlbl_idUsuario = new javax.swing.JLabel();
        jlbl_nomEquipo = new javax.swing.JLabel();
        jlbl_modeloEquipo = new javax.swing.JLabel();
        jlbl_numSerie = new javax.swing.JLabel();
        jrbtn_desifectante = new javax.swing.JRadioButton();
        jrbtn_inspSecado = new javax.swing.JRadioButton();
        jrbtn_empaquetado = new javax.swing.JRadioButton();
        jrbtn_almacenado = new javax.swing.JRadioButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_cancelar = new javax.swing.JButton();
        jlbl_equipo = new javax.swing.JLabel();
        jlbl_serie = new javax.swing.JLabel();
        jlbl_modelo = new javax.swing.JLabel();
        jlbl_marcaEquipo = new javax.swing.JLabel();
        jlbl_marca = new javax.swing.JLabel();
        jtxt_id = new javax.swing.JTextField();
        jtxt_idUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Proceso");
        setPreferredSize(new java.awt.Dimension(784, 770));

        jlbl_ingresarID.setText("Ingrese  ID Equipo:");

        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });

        jlbl_idUsuario.setText("Ingrese ID Usuario:");

        jlbl_nomEquipo.setText("Nombre Equipo:");

        jlbl_modeloEquipo.setText("Modelo Equipo:");

        jlbl_numSerie.setText("Numero Serie:");

        buttonGroupProceso.add(jrbtn_desifectante);
        jrbtn_desifectante.setText("Exposición Al Desinfecctante");

        buttonGroupProceso.add(jrbtn_inspSecado);
        jrbtn_inspSecado.setText("Inspección y Secado");
        jrbtn_inspSecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_inspSecadoActionPerformed(evt);
            }
        });

        buttonGroupProceso.add(jrbtn_empaquetado);
        jrbtn_empaquetado.setText("Empaquetado");

        buttonGroupProceso.add(jrbtn_almacenado);
        jrbtn_almacenado.setText("Almacenado");

        jbtn_actualizar.setText("Actualizar Proceso");
        jbtn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarActionPerformed(evt);
            }
        });

        jbtn_cancelar.setText("Cancelar");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        jlbl_marcaEquipo.setText("Marca Equipo:");

        jtxt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbl_modeloEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbl_nomEquipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlbl_modelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbl_equipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbl_numSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbl_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jlbl_marcaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlbl_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbl_idUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbl_ingresarID))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxt_id)
                                    .addComponent(jtxt_idUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addComponent(jbtn_buscar)
                                .addGap(106, 106, 106))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jrbtn_inspSecado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbtn_desifectante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbtn_empaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbtn_almacenado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbl_ingresarID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn_buscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_idUsuario)
                    .addComponent(jtxt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nomEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_numSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_modeloEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_marcaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtn_desifectante)
                    .addComponent(jrbtn_empaquetado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtn_inspSecado)
                    .addComponent(jrbtn_almacenado))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(800, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        this.jtxt_id.requestFocus();
        
        controlador.ContProceso proceso = new controlador.ContProceso();
        Equipo equip = new Equipo();
        TipoEquipo tipoequip = new TipoEquipo();
        Marca marc = new Marca();
        
        String id,equipo;
        int estado;
        
        try {
            
            if (jtxt_id.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar un ID!", "Atención",JOptionPane.WARNING_MESSAGE);
            }else{
                // convertir id en String para buscar en sql
                id = jtxt_id.getText();

                //con esto buscamos el equipo por el id y recuperamos la info
                equip = proceso.buscarenProceso(id);
                this.jlbl_modelo.setText(equip.getModelo());//aqui obtenemos el modelo del equipo

                // aca recuperamos el tipo según el id de tipo tomado antes
                tipoequip = proceso.buscartipo(equip.getId_tipo_equipo());
                this.jlbl_equipo.setText(tipoequip.getTipo_equipo());

                //aca recuperamos la marca segun el id tomado en el comienzo}
                marc = proceso.marca(equip.getId_marca());
                this.jlbl_marca.setText(marc.getNombre_marca());

                // aca definimos el numero de serie de lo recuperado con la busqueda del equipo por id
                this.jlbl_serie.setText(equip.getNumero_serie());
                
                if (this.jlbl_modelo.getText().isEmpty() && this.jlbl_equipo.getText().isEmpty() && this.jlbl_marca.getText().isEmpty() && this.jlbl_serie.getText().isEmpty()){
                    JOptionPane.showMessageDialog(rootPane, "Equipo no encontrado!", "Atención",JOptionPane.WARNING_MESSAGE);
                }


            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Equipo no encontrado!", "Atención",JOptionPane.WARNING_MESSAGE);
        }
//        indexModelo=equip.getId_tipo_equipo();
//        switch (indexModelo){
//            case 1:
//                tipoEquipo= "ENDOSCOPIO";
//                break;
//            case 2:
//                tipoEquipo= "COLONOSCOPIO";
//                break;
//            case 3:
//                tipoEquipo= "DUODENOSCOPIO";
//                break;
//            case 4:
//                tipoEquipo= "BRONCOSCOPIO";
//                break;
//            case 5:
//                tipoEquipo= "VIDEOBRONCOSCOPIO";
//                break;
//            case 6:
//                tipoEquipo= "VIDEOCOLEDOSCOPIO";
//                break;
//            case 7:
//                tipoEquipo= "TRANSDUCTOR LAPAROSCOPICO";
//                break;
//            case 8:
//                tipoEquipo= "TRANSDUCTOR TRANSESOFAGICO";
//                break;
//            case 9:
//                tipoEquipo= "CISTOSCOPIO";
//                break;
//            case 10:
//                tipoEquipo= "NASOFIBROSCOPIO";
//                break;
//            case 11:
//                tipoEquipo= "NASOLARINGOSCOPIO"; 
//                break;
//        }
//        
//        this.jlbl_modelo.setText(tipoEquipo);//para mostrar el modelo

        
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jrbtn_inspSecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_inspSecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn_inspSecadoActionPerformed

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jtxt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idActionPerformed

    private void jbtn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarActionPerformed
         Proceso proces = new Proceso();
        controlador.ContProceso agrega = new controlador.ContProceso();
        
        if (this.jtxt_id.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un ID!", "Atención",JOptionPane.WARNING_MESSAGE);
        }else {
            if(this.jtxt_idUsuario.getText().isEmpty()){
               JOptionPane.showMessageDialog(rootPane, "Debe ingresar un ID de usuario!", "Atención",JOptionPane.WARNING_MESSAGE); 
            }else{
                if (this.jlbl_modelo.getText().isEmpty() && this.jlbl_equipo.getText().isEmpty() && this.jlbl_marca.getText().isEmpty() && this.jlbl_serie.getText().isEmpty()){
                   JOptionPane.showMessageDialog(rootPane, "Debe corroborar los datos del ID", "Atención",JOptionPane.WARNING_MESSAGE); 
                }else{
                    int id = Integer.parseInt(this.jtxt_id.getText());
                    int idUser = Integer.parseInt(this.jtxt_idUsuario.getText());

                    int estado = 0;

                    if (this.jrbtn_desifectante.isSelected()) {
                        estado = 2;
                    } else {
                        if (this.jrbtn_inspSecado.isSelected()) {
                            estado = 3;
                        } else {
                            if (this.jrbtn_empaquetado.isSelected()) {
                                estado = 4;
                            } else {
                                if (this.jrbtn_almacenado.isSelected()) {
                                    estado = 5;
                                }
                            }
                        }
                    }

                    proces.setId_equipo(id);
                    proces.setId_usuario(idUser);
                    proces.setId_tipo_proceso(estado);

                    try {
                        agrega.agregarProceso(proces);
                        JOptionPane.showMessageDialog(rootPane, "Proceso Actualizado", "", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Proceso NO Actualizado", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                
            }
        }
        
       
    }//GEN-LAST:event_jbtn_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VProceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupProceso;
    private javax.swing.JButton jbtn_actualizar;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JLabel jlbl_equipo;
    private javax.swing.JLabel jlbl_idUsuario;
    private javax.swing.JLabel jlbl_ingresarID;
    private javax.swing.JLabel jlbl_marca;
    private javax.swing.JLabel jlbl_marcaEquipo;
    private javax.swing.JLabel jlbl_modelo;
    private javax.swing.JLabel jlbl_modeloEquipo;
    private javax.swing.JLabel jlbl_nomEquipo;
    private javax.swing.JLabel jlbl_numSerie;
    private javax.swing.JLabel jlbl_serie;
    private javax.swing.JRadioButton jrbtn_almacenado;
    private javax.swing.JRadioButton jrbtn_desifectante;
    private javax.swing.JRadioButton jrbtn_empaquetado;
    private javax.swing.JRadioButton jrbtn_inspSecado;
    private javax.swing.JTextField jtxt_id;
    private javax.swing.JTextField jtxt_idUsuario;
    // End of variables declaration//GEN-END:variables
}
